### ISSUE TITLE
Ambiguous use of 'subscript(_:)'

### ISSUE THREAD

**Issue by SENTINELITE** [bhsw/concurrent-websockets#4]
Hey there! 

Love the package! Just what I was looking for!

Running under Xcode 14+, I'm seeing this error "Ambiguous use of 'subscript(_:)'", on line 525 of Framing.swift.

This isn't an issue with Xcode 13. Just wanted to give a heads up!

![CleanShot 2022-08-31 at 17 00 49@2x](https://user-images.githubusercontent.com/44782976/187805369-6c7f0b0e-b738-4d8d-b91f-f0c1a6353ddb.png)

**Comment by rs70** [comment]
Thanks for pointing this out, and sorry for the delayed reply.

I added a release (v0.5.0) that should address this. Let me know if you still run into any problems.

**Comment by SENTINELITE** [comment]
That did the trick, thanks! I'll make a new issue if anything else arises.
